-- MySQL Script generated by MySQL Workbench
-- 12/14/20 19:49:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hack
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hack` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hack` ;

-- -----------------------------------------------------
-- Table `hack`.`hack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hack`.`hack` (
  `int` INT NOT NULL AUTO_INCREMENT,
  `info` VARCHAR(5000) NULL,
  `ip` VARCHAR(45) NULL,
  `data` VARCHAR(50) NULL,
  `pais` VARCHAR(45) NULL,
  `continente` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`int`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
